name: Openwrt Build Bot
on:
  push:
    branches: master
  schedule:
  - cron: 0 0 * * *

jobs:
  buildpkg:
    name: Build Openwrt Package
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        SDK_URL:
        - https://downloads.openwrt.org/releases/21.02.0-rc3/targets/ramips/mt7621/openwrt-sdk-21.02.0-rc3-ramips-mt7621_gcc-8.4.0_musl.Linux-x86_64.tar.xz
    steps:
    - uses: actions/checkout@master
    - name: Env for Openwrt SDK
      run: sudo apt install -y libev-dev libc-ares-dev libudns-dev libncurses-dev
    - name: Download Openwrt SDK
      env:
        SDK_URL: ${{ matrix.SDK_URL }}
      run: |
        SDK_HOME=$(head -c -8 <<< $(basename $SDK_URL))
        wget $SDK_URL
        tar xf $(basename $SDK_URL) -C ~/
        mv ~/$SDK_HOME ~/sdk
    - name: Download Packages
      run: |
        cd ~/sdk
        # Shadowsocks
        git clone -b master https://github.com/honwen/luci-app-shadowsocks-rust.git package/luci-app-shadowsocks-rust
        git clone -b master https://github.com/honwen/openwrt-shadowsocks-rust.git package/shadowsocks-rust
        git clone -b master https://github.com/aa65535/openwrt-simple-obfs package/simple-obfs
        git clone -b master https://github.com/aa65535/openwrt-dist-luci package/openwrt-dist-luci
        pushd package/openwrt-dist-luci/tools/po2lmo ; make && sudo make install ; popd
        ./scripts/feeds update -a
        ./scripts/feeds install golang c-ares libev libopenssl libsodium mbedtls pcre libncursesw6
        ./staging_dir/host/bin/usign -G -s ./key-build -p ./key-build.pub -c "Local build key"
    - name: Compile
      run: |
        cd ~/sdk
        make defconfig
        # Edit config
        make V=s
    - name: Upload
      env:
        SDK_URL: ${{ matrix.SDK_URL }}
        GITHUB_TOKEN: ${{ secrets.ACTION_DEPLOY_KEY }}
      run: |
        TAG=$(sed -n 's/.*targets\/\(\w*\)\/\(\w*\)\/.*/packages\/\1\/\2/p' <<< $SDK_URL)
        # Upload base only
        cd ~/sdk/bin/packages/*/base
        git init
        git config user.name "bot"
        git config user.email "bot@github.com"
        git add .
        git commit -m "$TAG$(TZ='Asia/Shanghai' date +@%Y%m%d)"
        git push --force --quiet "https://$GITHUB_TOKEN@github.com/riKirsti/freewrt.git" HEAD:$TAG
