name: Openwrt Build Bot
on:
  push:
    branches: master
  schedule:
  - cron: 0 0 * * 1,4
env:
  UPLOAD_RELEASE: true
jobs:
  buildpkg:
    name: Build Openwrt Package
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        SDK_URL:
        - https://downloads.openwrt.org/snapshots/targets/ramips/mt7621/openwrt-sdk-ramips-mt7621_gcc-11.3.0_musl.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/snapshots/targets/mediatek/mt7622/openwrt-sdk-mediatek-mt7622_gcc-11.3.0_musl.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/snapshots/targets/mediatek/filogic/openwrt-sdk-mediatek-filogic_gcc-11.3.0_musl.Linux-x86_64.tar.xz
    steps:
    - uses: actions/checkout@master
    - name: Env for Openwrt SDK
      run: |
        sudo apt-get clean
        sudo apt-get remove
        sudo apt-get update
        sudo apt-get upgrade -y
        sudo apt-get update
        sudo apt-get dist-upgrade -y
        sudo apt-get install -y build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc-s1 libc6-dev-i386 subversion git-core gcc-multilib libelf-dev autoconf automake libtool
        sudo apt-get install -y libev-dev libc-ares-dev libudns-dev libncurses-dev upx
    - name: Download Openwrt SDK
      env:
        SDK_URL: ${{ matrix.SDK_URL }}
      run: |
        SDK_HOME=$(head -c -8 <<< $(basename $SDK_URL))
        wget $SDK_URL
        tar xf $(basename $SDK_URL) -C ~/
        mv ~/$SDK_HOME ~/sdk
    - name: Download Packages
      run: |
        cd ~/sdk
        # Zerotier
        git clone --depth 1 -b master https://github.com/mwarning/zerotier-openwrt.git package/zerotier
        # Smartdns
        git clone --depth 1 -b master https://github.com/riKirsti/openwrt-smartdns.git package/smartdns
        # XRAY
        git clone --depth 1 -b master https://github.com/riKirsti/openwrt-xray.git package/xray-core
        git clone --depth 1 -b master https://github.com/honwen/luci-app-xray.git package/luci-app-xray
        # Clash
        git clone --depth 1 -b master https://github.com/vernesong/OpenClash package/openclash
        # Shadowsocks
        git clone --depth 1 -b master https://github.com/honwen/luci-app-shadowsocks-rust.git package/luci-app-shadowsocks-rust
        git clone --depth 1 -b master https://github.com/honwen/openwrt-shadowsocks-rust.git package/shadowsocks-rust
        git clone --depth 1 -b master https://github.com/aa65535/openwrt-simple-obfs.git package/simple-obfs
        pushd package/luci-app-shadowsocks-rust/tools/po2lmo ; make && sudo make install ; popd
        ./scripts/feeds update -a
        ./scripts/feeds install golang libev libpthread libopenssl
        ./staging_dir/host/bin/usign -G -s ./key-build -p ./key-build.pub -c "Local build key"
    - name: Compile
      run: |
        cd ~/sdk
        make defconfig
        # Edit config
        make V=s
    - name: Upload
      env:
        SDK_URL: ${{ matrix.SDK_URL }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        TAG=$(sed -n 's/.*targets\/\(\w*\)\/\(\w*\)\/.*/packages\/\1\/\2/p' <<< $SDK_URL)
        # Upload base only
        cd ~/sdk/bin/packages/*/base
        wget -O- 'https://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest' | awk -F\| '/(CN\|ipv4|HK\|ipv4|TW\|ipv4|JP\|ipv4|KR\|ipv4|SG\|ipv4|MO\|ipv4)/ { printf("%s/%d\n", $4, 32-log($5)/log(2)) }' > chinaroute.txt
        wget -O- 'https://raw.githubusercontent.com/cokebar/gfwlist2dnsmasq/master/gfwlist2dnsmasq.sh' > /tmp/gfwlist2dnsmasq.sh && chmod +x /tmp/gfwlist2dnsmasq.sh && sh /tmp/gfwlist2dnsmasq.sh -d 8.8.8.8 -p 53 -s xray_spec_src_fw -o xgw.txt && sed -i 's/server=/nameserver /g' xgw.txt && sed -i 's/8.8.8.8#53/gw/g' xgw.txt && sed -i 's/=/ /g' xgw.txt && rm -rf /tmp/gfwlist2dnsmasq.sh 
        wget -O- 'https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf' > /tmp/accelerated-domains.china.conf && sed -e 's|^server=/\(.*\)/114.114.114.114$|\1|' /tmp/accelerated-domains.china.conf | egrep -v '^#' > /tmp/accelerated-domains.china.raw.txt && sed -e "s|\(.*\)|domain-rules /\1/ -c ping,tcp:80 -n cn -p xray_spec_dst_bp|" /tmp/accelerated-domains.china.raw.txt > xcn.txt && rm -f /tmp/accelerated-domains.china*
        wget -O- 'https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/apple.china.conf' > /tmp/apple.china.conf && sed -e 's|^server=/\(.*\)/114.114.114.114$|\1|' /tmp/apple.china.conf | egrep -v '^#' > /tmp/apple.china.txt && sed -e "s|\(.*\)|domain-rules /\1/ -c ping,tcp:80 -n cn -p xray_spec_dst_bp|" /tmp/apple.china.txt > xapcn.txt && rm -f /tmp/apple.china.*
        wget -O- 'https://raw.githubusercontent.com/cokebar/gfwlist2dnsmasq/master/gfwlist2dnsmasq.sh' > /tmp/gfwlist2dnsmasq.sh && chmod +x /tmp/gfwlist2dnsmasq.sh && sh /tmp/gfwlist2dnsmasq.sh -d 8.8.8.8 -p 53 -s ss_spec_dst_fw -o sgw.txt&& sed -i 's/server=/nameserver /g' sgw.txt&& sed -i 's/8.8.8.8#53/gw/g' sgw.txt&& sed -i 's/=/ /g' sgw.txt&& rm -rf /tmp/gfwlist2dnsmasq.sh 
        wget -O- 'https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf' > /tmp/accelerated-domains.china.conf && sed -e 's|^server=/\(.*\)/114.114.114.114$|\1|' /tmp/accelerated-domains.china.conf | egrep -v '^#' > /tmp/accelerated-domains.china.raw.txt && sed -e "s|\(.*\)|domain-rules /\1/ -c ping,tcp:80 -n cn -p ss_spec_dst_bp|" /tmp/accelerated-domains.china.raw.txt > scn.txt && rm -f /tmp/accelerated-domains.china*
        wget -O- 'https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/apple.china.conf' > /tmp/apple.china.conf && sed -e 's|^server=/\(.*\)/114.114.114.114$|\1|' /tmp/apple.china.conf | egrep -v '^#' > /tmp/apple.china.txt && sed -e "s|\(.*\)|domain-rules /\1/ -c ping,tcp:80 -n cn -p ss_spec_dst_bp|" /tmp/apple.china.txt > sapcn.txt && rm -f /tmp/apple.china.*   
        git init
        git config user.name "bot"
        git config user.email "bot@github.com"
        git add *.ipk
        git add *.txt
        git commit -m "$TAG$(TZ='Asia/Shanghai' date +@%Y%m%d)"
        git push --force --quiet "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/riKirsti/freewrt.git" HEAD:$TAG
